### ISSUE TITLE
Problem when ble is activated then deactivated

### ISSUE THREAD

**Issue by aat-antoine** [AltBeacon/android-beacon-library#112]
Problem seen on the last version (2.1.2) on my N5 (5.0.1)

Here the stackTrace

```java
java.lang.IllegalStateException: BT Adapter is not turned ON
      at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
      at android.bluetooth.le.BluetoothLeScanner.stopScan(BluetoothLeScanner.java:144)
      at org.altbeacon.beacon.service.scanner.CycledLeScannerForLollipop.deferScanIfNeeded(CycledLeScannerForLollipop
      at org.altbeacon.beacon.service.scanner.CycledLeScanner.scanLeDevice(CycledLeScanner.java:165)
      at org.altbeacon.beacon.service.scanner.CycledLeScannerForLollipop$1.run(CycledLeScannerForLollipop.java:155)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:135)
      at android.app.ActivityThread.main(ActivityThread.java:5221)
      at java.lang.reflect.Method.invoke(Native Method)
      at java.lang.reflect.Method.invoke(Method.java:372)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

If i have some time, i will inspect this stackTrace but for now i keep logs in this issue :)

**Comment by davidgyoung** [comment]
Fixed in 50ccd89931872fddb5c27018aa7730f326a5ead0.  This was a copy/paste error created by the fix from #105
