### ISSUE TITLE
Android 13 Crash : Beacon service crash

### ISSUE THREAD

**Issue by pravingaikwad07** [AltBeacon/android-beacon-library#1158]
Is there any update on this issue : https://github.com/AltBeacon/android-beacon-library/issues/1141#issue-1710209091

Expected behaviour : Service should start when calling Context.startForegroundService()

Actual Behaviour : Throwing crash in the library as this exception is not handled

Steps to reproduce : Issue is happening when app is in background. Not able to reproduce this manually

Mobile device model and OS version : Crash is happening on android 12 on model Samsung Galaxy A23 5G, Galaxy A03s, Model:Moto G Pure and Android 13 on Model:Galaxy S21 FE 5G, Galaxy S22+, Model:Galaxy A42 5G, Model:Galaxy A53 5G

Android Beacon Library version implementation : 'org.altbeacon:android-beacon-library:2.19.5'

**Comment by pravingaikwad07** [comment]
Crash report 1:
`Fatal Exception: android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{6170cc7 u0 com.wrkspot.employee.prod/org.altbeacon.beacon.service.BeaconService}
       at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:2245)
       at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2216)
       at android.app.ActivityThread.-$$Nest$mthrowRemoteServiceException()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2508)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`

**Comment by pravingaikwad07** [comment]
So, does it mean that the improvements are available in 'org.altbeacon:android-beacon-library:**2.19.6** ?

**Comment by davidgyoung** [comment]
Yes

**Comment by pravingaikwad07** [comment]
Thanks for the quick reply. I appreciate it.

I will update on this thread if I find any solution to reduce the frequency of this issue. Also, I will try to post the frequency in decrease of crashes after upgrading 2.19.5 to 2.19.6 as you suggested.

**Comment by davidgyoung** [comment]
The improvement was introduced in 2.19, so you will only see a difference if compared inf 2.18.x with 2.19.x

**Comment by pravingaikwad07** [comment]
Ok. So I am currently using 2.19.5 and if I upgrade it to 2.19.6, then do you think that there will be improvements in overall frequency of this crash?

**Comment by pravingaikwad07** [comment]
Also, wanted to check that is there any plan to release the version 2.20 stable version? I can see that it's in beta version as of now.
