### ISSUE TITLE
Unexpected new behavior: startRangingBeacons in BeaconManager must be called on the main thread

### ISSUE THREAD

**Issue by gerardmundo-birket** [AltBeacon/android-beacon-library#1213]
This change probably comes from commit 6c0aa93c20aed6ec8def7f3b5739bd408da6b6fb "Merge branch 'bugfix/repeadly-scan-job-restart-on-navigation'"

### Expected behavior
No crash when calling startRangingBeacons from a non-UI thread. This was the case until pulling "recent" code changes.

### Actual behavior
Crash
java.lang.IllegalStateException: Method addObserver must be called on the main thread
	at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.kt:296)
	at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.kt:174)
	at org.altbeacon.beacon.powersave.BackgroundPowerSaverInternal.<init>(BackgroundPowerSaverInternal.java:44)
	at org.altbeacon.beacon.BeaconManager.ensureBackgroundPowerSaver(BeaconManager.java:2088)
	at org.altbeacon.beacon.BeaconManager.startRangingBeacons(BeaconManager.java:1186)

### Steps to reproduce this behavior
Call startRangingBeacons from a non-UI thread

### Mobile device model and OS version
Samsung Galaxy Tab Active2 on Android 8.1.0

### Android Beacon Library version
Latest code in repo

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by VolodaUa** [comment]
Hi @gerardmundo-birket 

Thanks for noticing it. I've created the pull request.

**Comment by davidgyoung** [comment]
probably just need to wrap the addObserver call in a block that forces it onto the UI thread

**Comment by davidgyoung** [comment]
Fixed in #1226

**Comment by davidgyoung** [comment]
This will be in 2.21.1-beta1 for testing

**Comment by davidgyoung** [comment]
@gerardmundo-birket and @VolodaUa please confirm you see this working in 2.21.1-beta1 and I will close this issue

**Comment by VolodaUa** [comment]
@davidgyoung  Checked. All good from my side.
