### ISSUE TITLE
Possible crash on BeaconTransmitter.stopAdvertising

### ISSUE THREAD

**Issue by ryazmin** [AltBeacon/android-beacon-library#157]
Java.lang.IllegalStateException: BT Adapter is not turned ON
       at android.bluetooth.le.BluetoothLeUtils.checkAdapterStateOn(BluetoothLeUtils.java:136)
       at android.bluetooth.le.BluetoothLeAdvertiser.stopAdvertising(BluetoothLeAdvertiser.java:155)
       at org.altbeacon.beacon.BeaconTransmitter.stopAdvertising(BeaconTransmitter.java:209)

**Comment by davidgyoung** [comment]
Fixed in #159
