### ISSUE TITLE
Xiaomi mi3 java.lang.SecurityException: You either need MANAGE_USERS or CREATE_USERS permission to: query user 	at android.os.Parcel.readException(Parcel.java:1620) 	at android.os.Parcel.readException(Parcel.java:1573) 	at android.os.IUserManager$Stub$Proxy.getUserInfo(IUserManager.java:693) 	at android.os.UserManager.getUserInfo(UserManager.java:666) 	at android.os.UserManager.isManagedProfile(UserManager.java:620) 	at lon.d(:com.google.android.gms:48) 	at com.google.android.gms.cast.service.CastRemoteControlNotificationIntentOperation.onHandleIntent(:com.google.android.gms:38) 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms:118) 	at byv.run(:com.google.android.gms:1864) 	at bys.run(:com.google.android.gms:1143) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 	at java.lang.Thread.run(Thread.java:818) 

### ISSUE THREAD

**Issue by brandonwong87** [AltBeacon/android-beacon-library#538]
### Android Beacon Library version

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
@brandonwong87, please open a new question on StackOverflow.com.
