### ISSUE TITLE
Another  java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by TonyTangAndroid** [AltBeacon/android-beacon-library#579]
### Expected behavior

Not Crash.

### Actual behavior

Crashed with the following stack trace:

> Caused by: java.util.ConcurrentModificationException
     at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
     at java.util.HashMap$KeyIterator.next(HashMap.java:1465)
     at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
     at java.util.ArrayList.<init>(ArrayList.java:191)
     at org.altbeacon.beacon.service.ScanState.applyChanges(ScanState.java:272)
     at org.altbeacon.beacon.service.ScanJobScheduler.applySettingsToScheduledJob(ScanJobScheduler.java:83)
     at org.altbeacon.beacon.service.ScanJobScheduler.applySettingsToScheduledJob(ScanJobScheduler.java:92)
     at org.altbeacon.beacon.BeaconManager.applyChangesToServices(BeaconManager.java:962)
     at org.altbeacon.beacon.BeaconManager.updateScanPeriods(BeaconManager.java:956)
     at org.altbeacon.beacon.BeaconManager.setBackgroundMode(BeaconManager.java:530)
     at org.altbeacon.beacon.powersave.BackgroundPowerSaver.onActivityResumed(BackgroundPowerSaver.java:66)
     at android.app.Application.dispatchActivityResumed(Application.java:216)
     at android.app.Activity.onResume(Activity.java:1312)
     at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:439)
     at com.microstrategy.usher.presentation.view.activity.PresenterActivity.onResume(PresenterActivity.java:26)
     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1354)
     at android.app.Activity.performResume(Activity.java:7079)
     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3620)
     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3685) 
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2898) 
     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
     at android.os.Handler.dispatchMessage(Handler.java:105) 
     at android.os.Looper.loop(Looper.java:164) 
     at android.app.ActivityThread.main(ActivityThread.java:6541) 

### Steps to reproduce this behavior
Could not find a stable to reproduce it.

### Mobile device model and OS version
Google Pixel Android 8.0
### Android Beacon Library version
2.12.2

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
Fixed in #588
