### ISSUE TITLE
A third java.util.ConcurrentModificationException 

### ISSUE THREAD

**Issue by TonyTangAndroid** [AltBeacon/android-beacon-library#587]
### Expected behavior
There should not be crashes on such error occurs.
### Actual behavior
Random crash.

### Steps to reproduce this behavior
Could not be stably reproduced.
### Mobile device model and OS version
 Nexus 5  Android 6.0.1
### Android Beacon Library version
2.12.2

Stacktrace:

> Fatal Exception: java.lang.RuntimeException: Unable to pause activity : java.util.ConcurrentModificationException
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3381)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
       at android.app.ActivityThread.-wrap13(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
       at java.util.HashMap$EntryIterator.next(HashMap.java:824)
       at java.util.HashMap$EntryIterator.next(HashMap.java:824)
       at java.util.HashMap.writeObject(HashMap.java:974)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1033)
       at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
       at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
       at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
       at org.altbeacon.beacon.service.MonitoringStatus.**saveMonitoringStatusIfOn**(Unknown Source)
       at org.altbeacon.beacon.service.ScanState.save(Unknown Source)
       at org.altbeacon.beacon.service.ScanState.applyChanges(Unknown Source)
       at org.altbeacon.beacon.service.ScanJobScheduler.applySettingsToScheduledJob(Unknown Source)
       at org.altbeacon.beacon.service.ScanJobScheduler.applySettingsToScheduledJob(Unknown Source)
       at org.altbeacon.beacon.BeaconManager.applyChangesToServices(Unknown Source)
       at org.altbeacon.beacon.BeaconManager.updateScanPeriods(Unknown Source)
       at org.altbeacon.beacon.BeaconManager.setBackgroundMode(Unknown Source)
       at org.altbeacon.beacon.powersave.BackgroundPowerSaver.onActivityPaused(Unknown Source)
       at android.app.Application.dispatchActivityPaused(Application.java:223)
       at android.app.Activity.onPause(Activity.java:1475)
       at android.support.v4.app.FragmentActivity.onPause(Unknown Source)
       at com.microstrategy.usher.presentation.view.activity.PresenterActivity.onPause(Unknown Source)
       at android.app.Activity.performPause(Activity.java:6363)

**Comment by davidgyoung** [comment]
Fixed in #588
