### ISSUE TITLE
java.lang.OutOfMemoryError: Could not allocate JNI Env on LG g4 Android 6.0

### ISSUE THREAD

**Issue by wnchen** [AltBeacon/android-beacon-library#594]
### Expected behavior
No Exception

### Actual behavior
09-13 13:52:52.378 28423 28423 E AndroidRuntime: java.lang.OutOfMemoryError: Could not allocate JNI Env
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at java.lang.Thread.nativeCreate(Native Method)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at java.lang.Thread.start(Thread.java:1063)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:607)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator.requestModelMapFromWeb(Unknown Source)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator.loadModelMap(Unknown Source)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator.<init>(Unknown Source)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at org.altbeacon.beacon.distance.ModelSpecificDistanceCalculator.<init>(Unknown Source)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at org.altbeacon.beacon.service.ScanJob.startScanning(Unknown Source)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at org.altbeacon.beacon.service.ScanJob.onStartJob(Unknown Source)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at android.app.job.JobService$JobHandler.handleMessage(JobService.java:126)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5525)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
09-13 13:52:52.378 28423 28423 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)

### Steps to reproduce this behavior
Could not be stably produced. 

### Mobile device model and OS version
device: LG G4
OS: Android 6.0

### Android Beacon Library version
2.12.3-beta2

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by davidgyoung** [comment]
@wnchen, I see that ScanJobs are used despite this being Android 6.0.  Do you have them turned on manually in your app?  By default these are only used in Android 8.0+
