### ISSUE TITLE
Android 8.0 crash

### ISSUE THREAD

**Issue by quzhipeng** [AltBeacon/android-beacon-library#652]
Caused by: java.lang.RuntimeException: Cannot get job id from manifest.  Make sure that the immediateScanJobId is configured in the manifest for the ScanJob.
at org.altbeacon.beacon.service.ScanJob.getJobIdFromManifest(ScanJob.java:312)
at org.altbeacon.beacon.service.ScanJob.getImmediateScanJobId(ScanJob.java:282)

version:51c3fff
meta-data android:name="immmediateScanJobId" android:value="208352939"

You add this code, but the word is used wrong.
immmediateScanJobId => immediateScanJobId

**Comment by davidgyoung** [comment]
Thanks for this report.  I'm working on a quick fix in #653.  Will push an update as soon as I fully test it.

**Comment by davidgyoung** [comment]
This is in a 2.13.1 release on JCenter and MavenCentral.  If you rebuild with that release you should be good.

**Comment by quzhipeng** [comment]
Thank you for your modification.
