### ISSUE TITLE
Crash with Android 7.0

### ISSUE THREAD

**Issue by jay2503** [AltBeacon/android-beacon-library#656]
### Expected behavior
No Crash

### Actual behavior
Crashing when app is in background.

### Steps to reproduce this behavior
Open app
Keep in background for few minutes, unlock device, it will crash app.

### Mobile device model and OS version
All devices with Android 7 and 7.1, No issues with Android 6.

### Android Beacon Library version
Latest.

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

### Crash Report
```
03-07 19:17:51.711 12276-12276/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.northcanal.nclass, PID: 12276
                                                   java.lang.RuntimeException: Unable to instantiate receiver org.altbeacon.beacon.startup.StartupBroadcastReceiver: java.lang.ClassNotFoundException: Didn't find class "org.altbeacon.beacon.startup.StartupBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.northcanal.nclass-1/base.apk"],nativeLibraryDirectories=[/data/app/com.northcanal.nclass-1/lib/arm, /system/lib, /vendor/lib]]
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3018)
                                                       at android.app.ActivityThread.-wrap18(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6146)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.altbeacon.beacon.startup.StartupBroadcastReceiver" on path: DexPathList[[zip file "/data/app/com.northcanal.nclass-1/base.apk"],nativeLibraryDirectories=[/data/app/com.northcanal.nclass-1/lib/arm, /system/lib, /vendor/lib]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3013)
                                                       at android.app.ActivityThread.-wrap18(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6146) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
03-07 19:31:14.096 13511-13542/com.northcanal.nclass E/chromium: [ERROR:instance.cc(49)] Unable to locate service manifest for metrics
03-07 19:31:14.096 13511-13542/com.northcanal.nclass E/chromium: [ERROR:service_manager.cc(890)] Failed to resolve service name: metrics
03-07 19:31:14.303 13511-13552/com.northcanal.nclass E/chromium: [ERROR:devtools_http_handler.cc(249)] Cannot start http server for devtools. Stop devtools.
03-07 19:31:14.432 13511-13556/com.northcanal.nclass E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
```

**Comment by davidgyoung** [comment]
This appears similar to #306, which could not find a different class on the classloader

I don't think this is universal for all devices with Android 7, as I have done plenty of tests unlocking the device on Android 7 with the reference app.   Something else must be triggering this.  I wonder if it might be proguard related?  Perhaps the class names have been obfuscated in the APK, and for some reason the obfuscated names are not used in some cases?
