### ISSUE TITLE
BeaconService "PackageManager has died" crash

### ISSUE THREAD

**Issue by nlasagni** [AltBeacon/android-beacon-library#661]
### Expected behavior
No crash

### Actual behavior
Library throws an "Unable to create service org.altbeacon.beacon.service.BeaconService: java.lang.RuntimeException: Package manager has died" and the app crash.

### Steps to reproduce this behavior
Not so reproducible, it happens for app that never starts the beacon scanning but initialize the BeaconManager.

### Mobile device model and OS version
Samsung Galaxy A5 Android 6

### Android Beacon Library version
2.12.3

StackTrace of the exception:

```
Fatal Exception: java.lang.RuntimeException: Unable to create service org.altbeacon.beacon.service.BeaconService: java.lang.RuntimeException: Package manager has died
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3883)
       at android.app.ActivityThread.access$2100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7331)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Caused by java.lang.RuntimeException: Package manager has died
       at android.app.ApplicationPackageManager.getServiceInfo(ApplicationPackageManager.java:491)
       at org.altbeacon.beacon.service.BeaconService.onCreate(BeaconService.java:220)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3873)
       at android.app.ActivityThread.access$2100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7331)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

Caused by android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:503)
       at android.content.pm.IPackageManager$Stub$Proxy.getServiceInfo(IPackageManager.java:3103)
       at android.app.ApplicationPackageManager.getServiceInfo(ApplicationPackageManager.java:486)
       at org.altbeacon.beacon.service.BeaconService.onCreate(BeaconService.java:220)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3873)
       at android.app.ActivityThread.access$2100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1909)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7331)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by inbeacon** [comment]
Same issue here. The only thing I could think of is that out customer went from APK to AAB publishing.
