### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=23; index=-2 at org.altbeacon.beacon.BeaconParser.getBeaconAdvertisementData(BeaconParser.java:672)

### ISSUE THREAD

**Issue by GregTBiba** [AltBeacon/android-beacon-library#747]
### Expected behavior
Ability for phone to Transmit as a Beacon

### Actual behavior
Upon trying to transmit, app is killed.

### Steps to reproduce this behavior
Please note this is Part of a plugin made for a unity game, besides that I followed the steps as outlined in [https://altbeacon.github.io/android-beacon-library/beacon-transmitter.html](https://altbeacon.github.io/android-beacon-library/beacon-transmitter.html)

Code that is Called:

`beacon  = new Beacon.Builder()
                .setId1(uuid)
                .setId2(Integer.toString(major))
                .setId3(Integer.toString(minor))
                .setManufacturer(0x004C)
                .setTxPower(-59)
                .setDataFields(Arrays.asList(new Long[] {0l}))
                .build();

        BeaconParser beaconParser = new BeaconParser().setBeaconLayout("m:0-3=4c000215,i:4-19,i:20-21,i:22-23,p:24-24");
        beaconTransmitter = new BeaconTransmitter(getApplicationContext(),beaconParser);
        Log.i(TAG, "Start Advertiseing " + beacon.toString());
        beaconTransmitter.startAdvertising(beacon);`

Stack Trace:

```
10-03 14:26:19.325 19676-19700/? D/BeaconParser: Parsing beacon layout: m:0-3=4c000215,i:4-19,i:20-21,i:22-23,p:24-24
10-03 14:26:19.329 19676-19700/? D/BeaconTransmitter: new BeaconTransmitter constructed.  mbluetoothLeAdvertiser is android.bluetooth.le.BluetoothLeAdvertiser@7346650
10-03 14:26:19.329 19676-19700/? I/Unity Beacon: Start Advertiseing id1: d2fd8856-fc48-4f60-bb80-083d84543a63 id2: 1 id3: 1
10-03 14:26:19.350 19676-19700/? E/Unity: AndroidJavaException: java.lang.ArrayIndexOutOfBoundsException: length=23; index=-2
    java.lang.ArrayIndexOutOfBoundsException: length=23; index=-2
        at org.altbeacon.beacon.BeaconParser.getBeaconAdvertisementData(BeaconParser.java:672)
        at org.altbeacon.beacon.BeaconTransmitter.startAdvertising(BeaconTransmitter.java:179)
        at org.altbeacon.beacon.BeaconTransmitter.startAdvertising(BeaconTransmitter.java:159)
        at org.altbeacon.beacon.BeaconTransmitter.startAdvertising(BeaconTransmitter.java:149)
        at com.bibaventures.UnityPlugins.AndroidBeacon.AndroidBeacon.StartBeacon(AndroidBeacon.java:67)
        at com.bibaventures.UnityPlugins.AndroidBeacon.AndroidBeaconPlugin.StartBeaconFromUnity(AndroidBeaconPlugin.java:26)
        at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
        at com.unity3d.player.UnityPlayer.c(Unknown Source:0)
        at com.unity3d.player.UnityPlayer$e$2.queueIdle(Unknown Source:72)
        at android.os.MessageQueue.next(MessageQueue.java:395)
        at android.os.Looper.loop(Looper.java:160)
    	at com.unity3d.player.U
```

### Mobile device model and OS version
Pixel 2 XL Android 9
Pixel 2 Android 8.1.0

### Android Beacon Library version
vs 2.15.1

IMPORTANT:  This forum is reserved for feature requests or reproducible bugs with the library itself.  If you need help with using the library with your project, please open a new question on StackOverflow.com.

**Comment by GregTBiba** [comment]
Ok I got it working, the issue seemed to come from the beacon layout (m:0-3=4c000215,i:4-19,i:20-21,i:22-23,p:24-24) and manufacturer settings (0x004C) as I was trying to emulate the iBeacon. Changed it back to default and it worked fine.
