### ISSUE TITLE
NullPointerException in ScanHelper.startAndroidOBackgroundScan()

### ISSUE THREAD

**Issue by adrinieto** [AltBeacon/android-beacon-library#780]
### Actual behavior

A client reported this issue: 

```
 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.bluetooth.le.BluetoothLeScanner.startScan(java.util.List, android.bluetooth.le.ScanSettings, android.app.PendingIntent)' on a null object reference
        at org.altbeacon.beacon.service.ScanHelper.startAndroidOBackgroundScan(ScanHelper.java:167)
        at org.altbeacon.beacon.service.ScanJob.startPassiveScanIfNeeded(ScanJob.java:140)
        at org.altbeacon.beacon.service.ScanJob.onStopJob(ScanJob.java:159)
        at android.app.job.JobService$1.onStopJob(JobService.java:76)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:117)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

### Mobile device model and OS version

Android 8.1

### Android Beacon Library version

2.15

#583 is almost the same issue. The commit that fixes this issue fix the stopScan() but not the startScan().

**Comment by adrinieto** [comment]
Yes, i will make a Pull Request in a while.
