### ISSUE TITLE
NullPointer when destroying BeaconService

### ISSUE THREAD

**Issue by Del-S** [AltBeacon/android-beacon-library#792]
Hello,

I'm testing new Pre-release (2.15.3-beta1) and I'm getting this **NullPointerException** when I'm destroying BeaconService.

```
java.lang.RuntimeException: Unable to stop service org.altbeacon.beacon.service.BeaconService@28ee2fe: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.altbeacon.bluetooth.BluetoothCrashResolver.stop()' on a null object reference
        at android.app.ActivityThread.handleStopService(ActivityThread.java:4114)
        at android.app.ActivityThread.-wrap27(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2025)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void org.altbeacon.bluetooth.BluetoothCrashResolver.stop()' on a null object reference
        at org.altbeacon.beacon.service.BeaconService.onDestroy(BeaconService.java:333)
```

Seems like **BluetoothCrashResolver** is created only for API under 21 but onDestroy does not check for this condition or if it exists.

**Comment by davidgyoung** [comment]
This was just fixed in #790, although it has not yet been put into a release.  It will be in 2.15.3
