### ISSUE TITLE
Android Pie (Nokia) - Foreground Scanning Service scans for sometime and then scanning stops when app is in background. 

### ISSUE THREAD

**Issue by shriharsha-bhagwat** [AltBeacon/android-beacon-library#807]
### Expected behavior
When Foreground scanning service is enabled it should scan always 

### Actual behavior 
Scanning works for sometime(1-2 hours) and then scanning stops when the app is kept in background for a long time. 

### Steps to reproduce this behavior 
Let the scan start and leave mobile idle for more than 2 hours. Scanning return empty list of beacons
I have attached code. 

### Mobile device model and OS version 
Nokia 6.1 Android PIe OS Version 9

### Android Beacon Library version 
2.15

My Code: How can i run the scanning for a long time (10-12 hours) continuously on Android 8 and Android 9?

    beaconManager = BeaconManager.getInstanceForApplication(context);
            beaconManager.getBeaconParsers().add(new BeaconParser().setBeaconLayout("m:2-3=0215,i:4-19,i:20-21,i:22-23,p:24-24"));
            beaconManager.setForegroundScanPeriod(1500);
            beaconManager.setBackgroundScanPeriod(1500);
            if (!beaconManager.isBound(this)) {
                String NOTIFICATION_CHANNEL_ID = BuildConfig.APPLICATION_ID;
                String channelName = "App Service";
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                    NotificationChannel chan = new NotificationChannel(NOTIFICATION_CHANNEL_ID, channelName, NotificationManager.IMPORTANCE_DEFAULT);
                    chan.setLightColor(Color.BLUE);
                    chan.setLockscreenVisibility(Notification.VISIBILITY_PRIVATE);
                    NotificationManager manager = (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);
                    assert manager != null;
                    manager.createNotificationChannel(chan);
                }
                Intent intent = new Intent(context, LandingScreen.class);
                PendingIntent pendingIntent = PendingIntent.getActivity(
                        context, 0, intent, PendingIntent.FLAG_UPDATE_CURRENT
                );
                NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(context)
                        .setLargeIcon(BitmapFactory.decodeResource(context.getResources(), R.mipmap.ic_launcher))
                        .setSmallIcon(R.drawable.ic_logo_notification)
                        .setContentTitle("Scanning")
                        .setContentText("You are clocked IN")
                        .setStyle(new NotificationCompat.BigTextStyle().bigText("You are clocked IN"))
                        .setContentIntent(pendingIntent)
                        .setAutoCancel(true)
                        .setChannelId(NOTIFICATION_CHANNEL_ID);
                beaconManager.enableForegroundServiceScanning(notificationBuilder.build(), 5455);
                beaconManager.bind(this);

**Comment by davidgyoung** [comment]
Thanks for this report.  I have not seen this before.

I will attempt to reproduce with the reference app with a foreground service enabled on a Nokia 6.1 plus with Android 9.

I'd be curious to know if you see anything special in LogCat (from the OS or from app logs) when the scans stops.  I understand this is difficult to capture this if it takes 12 hours for it to happen.

**Comment by davidgyoung** [comment]
Right before the above SecurityException happened, the library tried to stop and restart the scan per these log lines:

```
01-04 17:18:46.365  2145  2145 D CycledLeScanner: The next scan cycle would go over the Android N max duration.
01-04 17:18:46.365  2145  2145 D CycledLeScanner: Stopping scan to prevent Android N scan timeout.
```

This is a library feature that will stop a constant scan after 30 minutes if it is on Android N+ and then restart it.  But it seems in this case the new scan is blocked with that SecuirtyException.

**Comment by davidgyoung** [comment]
Reproduced the problem a second time -- it takes exactly 30 minutes to get this in the background.  

Then when I go to Settings -> Apps -> BeaconReference -> App permissions 

I can confirm that it says it has Location permission.

**Comment by davidgyoung** [comment]
Another test to see if scans are always blocked from starting in the background for foreground service apps on this device:

1. kill the app
2. Using adb, start the app with the screen off:
`adb shell  monkey -p org.altbeacon.beaconreference -c android.intent.category.LAUNCHER 1`
3. Verify scans actually detect becons.

This proves that the exception does not always happen for starting scans in the background with foreground services.

**Comment by android-bash** [comment]
Thanks for trying out to reproduce the issue. Yes it takes 30 minutes atleast to reproduce this issue. The code actually works good in Oreo (Tried in Pixel). But not sure why it does not behave the same in Pie (Tried in Nokia).

**Comment by android-bash** [comment]
Is there any solution which can be tried out to solve this issue? Please let me know.

**Comment by davidgyoung** [comment]
I would suggest testing a betweenScanPeriod of 100ms to see if this alters the behavior

**Comment by android-bash** [comment]
Okay i will try this out and get back to you.

**Comment by android-bash** [comment]
I tried this and still the same. It did not work for me. Not sure how to proceed. 

            beaconManager.setBackgroundBetweenScanPeriod(100);
            beaconManager.setForegroundBetweenScanPeriod(100);

**Comment by davidgyoung** [comment]
Discoveries from a few further tests:

1. Periodically turning off scanning with a between scan period of 100ms (as @android-bash  noted above) does not affect this issue.  When the next scan is started more than 5 minutes after the app is in the background, it fails with the same SecurityException described above.

2. Even if the app does not scan at all for the first five minutes of being in the background, as soon as it does start scanning (after being in the background > 5 minutes) it will get this exception.  I tested this by setting beaconManager.setForegroundBetweenScanPeriod(6*60*1000); then launching the app and putting it to the background.  As soon as the next scan started (6 minutes later) it was blocked with the same SecurityException.

3. If I change to `targetSdkVersion 27` instead of `targetSdkVersion 28` in build.gradle, this SecurityException goes away.  @android-bash, can you confirm this?

**Comment by davidgyoung** [comment]
I also verified that if you do not use foreground service scanning with the library and instead use the default job scheduler running scans every ~15 minutes, the scans do succeed without a SecurityException.   So the default behavior of the library without a foreground service works as expected with Android 9

So this appears to be that:

Apps targeting SDK 28 with a foreground service starting BLE scans after > 5 minutes of running in the background on Android 9 will get a SecurityException trying to start a BLE scan.  (Only seen so far on Nokia Android Pie ROMs) 

It is unclear if this is an intended behavior of Android 9 or if it is a bug in AOSP or the Nokia ROMs.

While Nokia Android Pie ROMs are part of AndroidOne, so supposedly stock AOSP, if anybody has a Pixel device with Android 9.0 test this with, I'd love to get a confirmation of whether the problem exists there.

**Comment by android-bash** [comment]
I can verify in Google pixel today. And also if i run scans every 25 minutes using AlarmManager or Job Scheduler, what will be the behaviour? Will scans run continuously or will there be gaps in scan results as scheduler execution might be varied?

**Comment by carbonaro** [comment]
I tried the same with a OnePlus 5T running Android 9.0 and it works fine too. targetSdkVersion is 28, using a foreground service, scanning is still running after 45+ minutes with app in background, and screen off

**Comment by davidgyoung** [comment]
This was logged with Nokia [here](https://community.phones.nokia.com/discussion/40040/share-if-any-bugs-found-in-nokia-6-1-plus-after-pie-update) and in an email to support.  Unfortunately, I am told by their support they do not have a public bug reporting system.

**Comment by android-bash** [comment]
Yeah seems like bug in Nokia. Will try to get around it as you have said and will get back to you. @davidgyoung Thank you for all your inputs.

**Comment by android-bash** [comment]
I tried with targetSdkVersion 27. I see scanning gaps when phone goes to background.

**Comment by davidgyoung** [comment]
@android-bash, I received a reply from Nokia support, and they suggested doing the following:

- Settings/ Security and location/ Location/ Advanced/ Scanning/ disable Bluetooth scanning.
- Settings > Apps and notifications > See all apps > Three dots in the upper right corner > Show system > Bluetooth > Storage > Clear data and Clear Cache
- Settings > Apps and notifications > See all apps > Three dots in the upper right corner > Show system > Bluetooth MIDI > Storage > Clear data and Clear Cache
- Settings > Apps and notifications > See all apps > Google Play Services > Storage > Clear data and Clear Cache
- After that, please do a Soft reset - press volume up and power button together for 10 seconds.(Please have in mind that Soft reset will not erase your data.)

I performed the steps above to humor them, but to my surprise, I can no longer reproduce the problem on my Nokia 6.1 Plus 9.0.  This won't do anything to fix such problems with the wider user base (good luck getting all Nokia users to do this)  but it suggests the problem has something to do with phone state.  

Can you please try the above and see if you can confirm the same?

For what it's worth, after the problem went away, I re-enabled bluetooth scanning per the first step, rebooted, and confirmed I was still able to scan for more than 5 minutes with the screen off with a foreground service.

**Comment by android-bash** [comment]
Wow something to try out. I will also try this and get back to you. Thanks @davidgyoung

**Comment by davidgyoung** [comment]
@android-bash, please do try the steps above when you have a chance and let me know the result, I'd like to get confirmation if this helps from more than one affected device.

**Comment by android-bash** [comment]
@davidgyoung Sorry i did not have access to Nokia device from past few days. Tomorrow i will try this out and get back to you.

**Comment by joew46167** [comment]
Wow, I just read this, and really all I can say is wow.  

Since it looks like a security issue, have you tried to query the Location (and potentially phone state) permissions again during the process in which you stop and restart the scanning?  I wonder if that would have any affect?  We all know that it probably shouldn't... but I'd still be tempted to see if it makes a difference.  Maybe Nokia is putting some kind of timeout on the permission duration?  I've known Nokia to have different interpretations of specs before, and would not put it past them.

**Comment by davidgyoung** [comment]
@joew46167, I did check permissions when the phone was in this state of blocking scans, and the OS reported then as being granted.  Based on my comment from Nokia support, I did see that doing their Bluetooth reset procedure made the problem go away.  I would like somebody else to repeat this to confirm, but if it is confirmed this suggests a bug triggered by  stateful condition and not intended behavior.

**Comment by davidgyoung** [comment]
And to answer your other questions, I have not been able to reproduce the problem since the reset procedure.  I highly doubt there is a programmatic way to do the same.

**Comment by joew46167** [comment]
Thanks for the information David. 

My app is designed for blind people to use.  That procedure would be difficult for them to follow.  So if I can’t reproduce the issue after running the procedure, I’d rather not run it until I exhaust all other options.  I’d like to continue testing.  So for that reason I’m hesitant to run the procedure at this time.  The rest of my team concurs.  

Tomorrow I’ll have a Pixel 2 to test with.  I hope that you’re correct and it works better. 

Again, thanks for your help.  

Joe

Sent from my iPhone

On Jan 17, 2019, at 3:44 PM, David G. Young <notifications@github.com> wrote:

And to answer your other questions, I have not been able to reproduce the problem since the reset procedure. I highly doubt there is a programmatic way to do the same.

**Comment by joew46167** [comment]
David

I don't have access to the Nokia phone today, so testing with that will have to until Monday.

I may not have access to the Pixel 2 ether. :(

**Comment by joew46167** [comment]
I'm testing today with a Samsung Galaxy Note 9 with Oreo 8.1 API 27.  As soon as the screen gets turned off the scanning stops immediately.  When I turn the screen back on it starts right up.  But many blind people leave the screen off - no need to have that battery draw.  I checked the battery save settings, and it looks like battery save setting is not the issue.

I'm also testing with a Samsung Galaxy Nexus with Marshmallow 6.0.1 API 23.  So far that looks to run wonderfully.

**Comment by davidgyoung** [comment]
@joew46167, let's keep this issue focussed on the  Nokia Pie / Nokie Android 9 scanning problem.  For info on Samsung 8.1 scanning, please see #769. The problem you described with that was fixed in 2.15.3.

**Comment by joew46167** [comment]
@davidgyoung A couple of times in this thread it shows a log where the issue is that the app no longer has location permission.  Does this bubble up to the app in any manner?  I haven't really figured out how to see the error condition at the app level.  (Sorry if I'm missing something obvious here.)

**Comment by davidgyoung** [comment]
The error appears in LogCat, but there is no exception received at the app level.  Scan results just stop.  And again, even if you programmatically check to see if the COARSE_LOCATION permission has been granted, the OS tells you it has.

**Comment by joew46167** [comment]
@davidgyoung have you done any testing on your Nokia phone since you showed that procedure? Does it still seem to be persistent?

**Comment by davidgyoung** [comment]
@joew46167, yes, I have done testing since then, and the issue described in this thread is now gone.  It disappeared right after performing the bluetooth reset steps suggested by Nokia and has not returned since.  That's good and bad news -- bad because I can no longer use my device to investigate automated solutions to the problem.

**Comment by joew46167** [comment]
@davidgyoung That's why I'm hesitant to do it.  I'm stubborn and not yet ready to stop trying to find a better way.  

An interesting thing - before I found your library, I created my own.  It worked pretty well, but had some stability issues.  I was hoping that moving to the beacon would help with those stability issues.  so I started the migration.  

I didn't have the Nokia phone yet when I started the process.  ad I had been doing most of my testing with the "keep screen on while charging" option turned on.  and I have the phone connected for logging, so it was always charging.  So it took a while before I ever saw the issue.

Now I've gone back for a bit to using my old code, just to see what happens.  I had also found by trial and error that I needed to stop and restart scanning periodically.  The bad news in my old code is that after the screen is off, the scans stop, and I get the same COARSE_LOCATION error message.  the good news in my old phone, though, is that when I turn the screen back on it appears to recover, although I admittedly need to do some longer duration testing yet.  I wonder if maybe I inadvertently stumbled on a way around this?  I'll let you know more tomorrow.

Lastly, if you were to do a factory reset, would you get the issue back so you could resume investigation?  I'm guessing you've already tried that.

**Comment by davidgyoung** [comment]
I did not try a factory reset.  I suspect however that a factory reset would have also cleared the error condition in a way similar to resetting the Bluetooth settings.

I say this because the error condition happened right after the Android Pie upgrade.  I suspect the upgrade process is at fault, basically retaining Bluetooth state data from Android 8 that does not work properly with Android Pie on Nokia phones.

Juat a theory.

**Comment by joew46167** [comment]
@davidgyoung Hate to say it, because I hate disagreeing with smarter people, but I think your theory ay be wrong.  And here's why.

I got my unlocked Nokia 7.1 in mid December.  During the setup procedure it did an upgrade to Pie,  So I've never done anything with this phone that wasn't done on Pie, and I'm still seeing the issue,  I don't think there could have been any data on my phone to retain from Oreo.  Granted I could be wrong.  But my gut feeling is after a factory reset and getting to Pie again, even without running anything Bluetooth pre-Pie you'll see the issue.

Just my feeling.

**Comment by joew46167** [comment]
@davidgyoung Is there any way to accelerate testing?  That half an hour before the issue occurs is tough!

**Comment by joew46167** [comment]
Hello @davidgyoung 

I never did do the ugly "fix" procedure that you got from Nokia.  However yesterday I did do a factory reset of the phone, and the issue is still present.  IDK if that is useful information for you.

**Comment by cobainmo** [comment]
I have same issue. Using library in foreground service and it works like a charm some time and then it stops scan for a while and start again. I have same behaviour on 3 different devices (Moto Z Play 8.0, Samsung A7 8.0 and Nokia8 9.0). Only thing i get from log is:

> 01-28 14:01:38.099 5651-6767/nsoft.navi.claim.claimerwmp D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=5 mScannerId=0
01-28 14:01:39.204 5651-7693/nsoft.navi.claim.claimerwmp D/BluetoothAdapter: isLeEnabled(): ON
01-28 14:01:42.217 5651-5651/nsoft.navi.claim.claimerwmp I/ScanJob: Scan job runtime expired: org.altbeacon.beacon.service.ScanJob@de707cf
01-28 14:01:42.224 5651-7693/nsoft.navi.claim.claimerwmp D/BluetoothAdapter: isLeEnabled(): ON
01-28 14:01:42.225 5651-7693/nsoft.navi.claim.claimerwmp D/BluetoothLeScanner: could not find callback wrapper
01-28 14:01:42.587 5651-5651/nsoft.navi.claim.claimerwmp I/ScanJob: Using immediateScanJobId from manifest: 208352939
01-28 14:01:42.596 5651-5651/nsoft.navi.claim.claimerwmp I/ScanJob: Using periodicScanJobId from manifest: 208352940
01-28 14:01:42.596 5651-5651/nsoft.navi.claim.claimerwmp W/JobInfo: Requested interval +5m0s0ms for job 208352940 is too small; raising to +15m0s0ms
    Requested flex 0 for job 208352940 is too small; raising to +5m0s0ms
01-28 14:01:42.831 5651-5651/nsoft.navi.claim.claimerwmp I/CycledLeScanner: Using Android O scanner
01-28 14:01:42.838 5651-5651/nsoft.navi.claim.claimerwmp I/ScanJob: Using immediateScanJobId from manifest: 208352939
    Running immediate scan job: instance is org.altbeacon.beacon.service.ScanJob@2c0300
    scanJob version 2.15 is starting up on the main process

Any suggestion on how i could fix this?

Thanks

**Comment by joew46167** [comment]
@cobainmo 

For the Nokia phone I'm still searching for a good way around this.  I'm starting to lean toward detect and report.

I'm a little surprised by the Moto Z, but it is what I've had the least testing time with.

As for the Samsung, as David mentioned earlier, you can see #769 - which basically says to make sure you're using the latest version of the library.  

Lastly, David has asked that we limit this issue to Nokia phones.

**Comment by cobainmo** [comment]
@joew46167 Thanks. i was using 2.15 instead of 2.15.2. Will try that. 

Since Nokia was accused for having too aggressive background task manager (package: com.evenwell.powersaving.g3) that kills background activity of some apps after 20 minutes , maybe it can be one of the reasons for lib issue.

**Comment by joew46167** [comment]
@cobainmo  I even had trouble with 2.15.2.  I went all the way to 2.15.4

**Comment by davidgyoung** [comment]
@cobainmo, any issues with Samsung, please comment on #769. The core issue may be entirely different on each manufacturer phone.  Feel free to open a new issue for the Moto Z, but please make sure any logs you post are for the specific device associated with the issue.  It is also very helpful if you include system-level logs in your excerpts (not just log lines originating from your app process) because system level logs from the bluetooth stack often give clues to what is going on.  An example is the Nokia system log line about permissions mentioned [above](https://github.com/AltBeacon/android-beacon-library/issues/807#issuecomment-451587832).

Finally, please keep this issue focussed on Nokia so we don't confuse ourselves.

**Comment by joew46167** [comment]
@davidgyoung 

I just saw this [Nokia Security update](https://www.nokia.com/phones/en_int/security-updates) article.

Do you have any sight into what is happening at Nokia to know if this will address this issue?

**Comment by davidgyoung** [comment]
Unfortunately, I see nothing in the descriptions of those security patches that looks like they would address this issue.

**Comment by joew46167** [comment]
@davidgyoung H.  I'm not sure what you'll be able to do with this, but I'm sharing it with you anyway.

On my Nokia 7.1 running Pie, I went though the procedure you put in a [comment above](https://github.com/AltBeacon/android-beacon-library/issues/807#issuecomment-452883495), my plan being to do a factory rest later to see if this issue comes back.  However, I still get the same results - after about 10 minutes with the screen off I start seeing

```
01-30 13:48:23.712 5075-5701/org.aph.nearbyonline.debug W/Binder: Binder call failed.
   java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
      at android.os.Parcel.createException(Parcel.java:1950)
      at android.os.Parcel.readException(Parcel.java:1918)
      at android.os.Parcel.readException(Parcel.java:1868)
      at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:947)
      at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onScannerRegistered(BluetoothLeScanner.java:460)
      at android.bluetooth.le.IScannerCallback$Stub.onTransact(IScannerCallback.java:57)
      at android.os.Binder.execTransact(Binder.java:731)
```
and after 30 minutes I no longer get any ranging information.

One thing that I didn't expect - after the soft reset the screen showed a sick Android with it's chest open and the words No Command on the screen.  I'm not sure what that was about.  I had to power off and on again.  I thought maybe I missed something, so I went through the entire process a second time with the same results.

I haven't bothered with a factory reset.

**Comment by davidgyoung** [comment]
@joew46167, this suggests that the procedure from Nokia is not 100% effective.   Since you repeated it twice, this makes it unlikely that you accidentally skipped a step.

For the record, I did not see a "No Command" Android graphic like you describe when I went through the procedure.

**Comment by cobainmo** [comment]
I can also confirm that above procedure with clearing cache is not working on Nokia 8 Android 9 (with latest security patch installed) along with soft reset. I didn't have issue like @joew46167 it started normally, but i still keep getting "Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results".

@davidgyoung since i am trying to switch app from using "Estimote" library to AltBeacon i can confirm you that this issue does not occur on Estimote and Beacon scanner is working properly. I dont know if it helps you but id does not seem its just Nokia issue.

**Comment by cobainmo** [comment]
Hello, is there any new info about this issue?

Last 5 days i was running test on few Nokia devices as well as other manufacturers with android 9. Problem is definitely related to Nokia. On other vendors works fine. On the other side, Estimote lib still works on Nokia 8, Nokia 7.1 with android 9 so it got to be related to Altbeacon lib. 

Log:

> 02-04 12:01:33.870 28045-28045/nsoft.navi.claim.claimerwmp E/CycledLeScannerForLollipop: Scan failed: a BLE scan with the same settings is already started by the app
02-04 12:01:33.969 31631-31647/? V/FA: Inactivity, disconnecting from the service
02-04 12:01:38.932 990-1122/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
02-04 12:01:42.949 28045-28491/nsoft.navi.claim.claimerwmp D/BluetoothAdapter: isLeEnabled(): ON
02-04 12:01:42.959 28045-28491/nsoft.navi.claim.claimerwmp D/BluetoothAdapter: isLeEnabled(): ON
02-04 12:01:42.967 6288-6327/? I/bt_stack: [INFO:gatt_api.cc(949)] GATT_Register4b7a2d5f-3f1f-22de-3261-c1ea920ff9f7
    [INFO:gatt_api.cc(969)] allocated gatt_if=5
02-04 12:01:42.968 28045-31707/nsoft.navi.claim.claimerwmp D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=5 mScannerId=0
02-04 12:01:42.978 28045-31707/nsoft.navi.claim.claimerwmp W/Binder: Binder call failed.
    java.lang.SecurityException: Need ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission to get scan results
        at android.os.Parcel.createException(Parcel.java:1950)
        at android.os.Parcel.readException(Parcel.java:1918)
        at android.os.Parcel.readException(Parcel.java:1868)
        at android.bluetooth.IBluetoothGatt$Stub$Proxy.startScan(IBluetoothGatt.java:947)
        at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.onScannerRegistered(BluetoothLeScanner.java:460)
        at android.bluetooth.le.IScannerCallback$Stub.onTransact(IScannerCallback.java:57)
        at android.os.Binder.execTransact(Binder.java:731)
02-04 12:01:43.536 1448-1607/? I/ActivityManager: Start proc 31710:n.home.smartapp/u0a262 for broadcast n.home.smartapp/.widget.WidgetProvider
02-04 12:01:43.536 1448-1607/? D/ActivityManager: handleProcessStartedLocked mDoneFinishBooting && app.pid != 0 ---> notifyProcessStart, app.processName = n.home.smartapp, app.info = ApplicationInfo{4fe5261 n.home.smartapp}, app.hostingType = broadcast, getHostingName() = ComponentInfo{com.google.android.dialer/com.android.voicemail.impl.StatusCheckJobService}, getIntentFlag() = 0, getIsPackageRunning() = false, app = ProcessRecord{568d186 31710:n.home.smartapp/u0a262}, getExtraData() = Bundle[{SERVICE_INTENT=Intent { cmp=com.google.android.dialer/com.android.voicemail.impl.StatusCheckJobService }, CALLER_PACKAGE=android}]
02-04 12:01:43.537 1448-2414/? V/ActivityManager: notifyProcessStart: n.home.smartapp for: broadcast from: android packageName: com.google.android.dialer className: com.android.voicemail.impl.StatusCheckJobService
02-04 12:01:43.547 31710-31710/? E/n.home.smartap: Not starting debugger since process cannot load the jdwp agent.
02-04 12:01:43.549 22363-22363/? I/BgTaskExecutorImpl: Starting PERIODIC background task REFRESH_SEARCH_HISTORY.
02-04 12:01:43.557 1448-1607/? I/ActivityManager: Start proc 31723:com.google.android.dialer/u0a86 for service com.google.android.dialer/com.android.voicemail.impl.StatusCheckJobService
02-04 12:01:43.557 1448-1607/? D/ActivityManager: handleProcessStartedLocked mDoneFinishBooting && app.pid != 0 ---> notifyProcessStart, app.processName = com.google.android.dialer, app.info = ApplicationInfo{26cb39d com.google.android.dialer}, app.hostingType = service, getHostingName() = ComponentInfo{com.google.android.dialer/com.android.voicemail.impl.StatusCheckJobService}, getIntentFlag() = 0, getIsPackageRunning() = false, app = ProcessRecord{f708012 31723:com.google.android.dialer/u0a86}, getExtraData() = Bundle[{SERVICE_INTENT=Intent { cmp=com.google.android.dialer/com.android.voicemail.impl.StatusCheckJobService }, CALLER_PACKAGE=android}]
02-04 12:01:43.558 1448-2414/? V/ActivityManager: notifyProcessStart: com.google.android.dialer for: service from: android packageName: com.google.android.dialer className: com.android.voicemail.impl.StatusCheckJobService
02-04 12:01:43.569 3102-3102/? E/CarrierServices: [2] ben.F: Cannot access P-CSCF address, RCS configuration is null!
02-04 12:01:43.570 3102-3102/? E/CarrierServices: [2] ben.A: Cannot access P-CSCF port, IMS configuration is null!

**Comment by joew46167** [comment]
@cobainmo To be honest, I've moved on, and have just put in a check to see it still connected to the beacon scanned, and if not I tell the user (my app speaks anyway, as it is for blind people) that if they turn the screen on for a moment it will likely solve the issue.

It is interesting that the Estimate API has found a way around this. I wonder if it might have to do with frequency of restarting the scan?  I believe that the library is currently restarting every 29 minutes - just often enough to circumvent the 30 minute issue.  After my testing, my gut feeling (with no true evidence or testing) is twofold: 

1. That even if the timer had been only 10 minutes this issue would still be present
2. A more frequent scan update - say every 1 minute - might work

I also have a feeling that Google will catch on to our attempts to circumvent the 30 minute limit and shut that down, too.

**Comment by davidgyoung** [comment]
@joew46167 why do you think restarting a scan every 1 min would help?  

I am certainly open to ideas like this to try, as I don't know what is different about the estimote approach that would make it work.  (They might not know either, it is probably by accident!)

**Comment by joew46167** [comment]
@davidgyoung I'm about to do a test, but if I remember correctly, my hand built BLE code didn't have this issue with Nokia phones. And I was doing restarts every minute.  

It's been a while since I've used that code, I've slept since then, and I just can't be sure if I had the issue or not. As I said, though, I am going back to that code now and testing - I have other tests to do in that code as well.  I'll let you know the results.

**Comment by cobainmo** [comment]
@davidgyoung i think you are right about Estimote and accident since they have other more obvious issues unsolved.

Anyway this lib works great and i will leave estimote just for Nokia phones for now. If in some future you find out solution let me know.

@joew46167 i'm moving on too :) at some point i just doubted that it is only Nokia issue. After all testing, looks like i was wrong.

**Comment by joew46167** [comment]
@cobainmo I worry that your fear could be correct, that it's not just for Nokia, so I left my code agnostic - I do the check and make the suggestion to unlock the device for all devices, not just Nokia.

**Comment by joew46167** [comment]
@davidgyoung My memory was wrong.  My hand rolled BLE handler does indeed fail and presents the permissions error.  In it I restart the scanner every minute.  At the 10 minute mark is when the permissions error occurs.

I wonder if the Estimote library found a way to not require the periodic restart, and that is how they bypass the issue?

**Comment by jochemc** [comment]
I had the same issue (with my own code). In addition, I had my app being killed after some time (I am using the Foreground service approach). After some searching, the latter apparently was due to aggressive service killing on the Nokia, as reported here: https://dontkillmyapp.com/nokia. Killing the killer as instructed on that site fixed this, but also appears to silence the issue being reported/discussed in this thread (ie I saw no more scan security exceptions). I have no time to further investigate or reproduce this, but it may be a useful piece of information, hence this post.

**Comment by android-bash** [comment]
For me the Settings provided by Nokia (clearing storage etc) did not work on my Nokia 6.1 running Android 9. What worked is force stopping the PowerSaver.G3 system app inside Nokia.

**Comment by paulpv** [comment]
I just noticed the following in the reference app's manifest, maybe it would resolve this issue?
```xml
        <!-- uncomment the following to enable scanning for over 30 minutes on Android 7+ -->
        <service android:name="org.altbeacon.beacon.service.BeaconService"
            tools:node="replace">
            <meta-data android:name="longScanForcingEnabled" android:value="true"/>
        </service>
```

**Comment by tc14077** [comment]
Any updates on this issue? HMD Global (i.e. Nokia) claims to disable Evenwell powersaving apps on all devices running Android Pie or newer which means the foreground scanning service may be able to run in background.
I tested my app on a Nokia phone(Nokia 7.2 with the latest android version). My app is able to run in the background for more than an hours. However, the beacon scanning(with using Foreground Service Scanning approach) is found to be stopped after 30 minutes background operation.
