### ISSUE TITLE
CycledLeScanner.java line 516 org.altbeacon.beacon.service.scanner.CycledLeScanner.cleanupCancelAlarmOnUserSwitch

### ISSUE THREAD

**Issue by PongPloy2016** [AltBeacon/android-beacon-library#889]
I use android device HUAWEI Y9 2019  and ran  application   when I call  to connect Beacon  

and wait show error  logcat 

![Screen Shot 2562-06-04 at 15 40 20](https://user-images.githubusercontent.com/8625469/58864517-17678500-86df-11e9-80f1-aa724de5f8af.png)

Fatal Exception: java.lang.IllegalArgumentException: Receiver not registered: org.altbeacon.beacon.service.scanner.CycledLeScanner$3@15568d0
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1316)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1665)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:645)
       at org.altbeacon.beacon.service.scanner.CycledLeScanner.cleanupCancelAlarmOnUserSwitch(CycledLeScanner.java:516)
       at org.altbeacon.beacon.service.scanner.CycledLeScanner.destroy(CycledLeScanner.java:279)
       at org.altbeacon.beacon.service.ScanJob.stopScanning(ScanJob.java:184)
       at org.altbeacon.beacon.service.ScanJob.access$800(ScanJob.java:40)
       at org.altbeacon.beacon.service.ScanJob$1$1.run(ScanJob.java:100)
       at android.os.Handler.handleCallback(Handler.java:809)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7555)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

Thank You

**Comment by jmvines** [comment]
Same issue here

**Comment by PongPloy2016** [comment]
> Same issue here

 Wow  thank you to edit

**Comment by PongPloy2016** [comment]
@Ok thank you  @davidgyoung  I ad to edit code   and  I  will try the test again   

Thank you for Answer to help me 

<img width="1144" alt="Screen Shot 2562-06-05 at 10 22 13" src="https://user-images.githubusercontent.com/8625469/58928396-89da7280-877c-11e9-902c-32328c4fab24.png">

**Comment by davidgyoung** [comment]
@PongPloy2016, can you please try this beta release that fixes this problem and let me know if you no longer see the crash:

https://github.com/AltBeacon/android-beacon-library/releases/tag/2.16.3-beta1
